### ISSUE TITLE
Cannot make user - ‘print_ip’ used but never defined

### ISSUE THREAD

**Issue by CimStordal** [andikleen/simple-pt#1]
When I try to run "make user" on an Ubuntu 32bit 14.04.3 system I get this error:

useruser@ubuntu:~/simple-pt$ make user
cc -g -Wall -I ../processor-trace/libipt/include   -c -o sptdecode.o sptdecode.c
sptdecode.c:134:13: error: conflicting types for ‘print_ip’
 static void print_ip(uint64_t ip, unsigned long cr3)
             ^
sptdecode.c:90:13: note: previous declaration of ‘print_ip’ was here
 static void print_ip(uint64_t ip, uint64_t cr3);
             ^
sptdecode.c: In function ‘print_ip’:
sptdecode.c:140:4: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
    printf("+%ld", ip - sym->val);
    ^
sptdecode.c:142:3: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
   printf("%lx", ip);
   ^
sptdecode.c: In function ‘print_insn’:
sptdecode.c:232:3: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
   insn_class(insn->iclass));
   ^
sptdecode.c:232:3: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
sptdecode.c: In function ‘remove_loops’:
sptdecode.c:297:7: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
       insn, l[j].iterations);
       ^
sptdecode.c:297:7: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
sptdecode.c: In function ‘decode’:
sptdecode.c:401:4: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
    printf("%lx: sync forward: %s\n", pos, pt_errstr(pt_errcode(err)));
    ^
sptdecode.c:482:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
     pt_errstr(pt_errcode(err)));
     ^
sptdecode.c:482:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
sptdecode.c: At top level:
sptdecode.c:90:13: warning: ‘print_ip’ used but never defined [enabled by default]
 static void print_ip(uint64_t ip, uint64_t cr3);
             ^
make: **\* [sptdecode.o] Error 1

**Comment by andikleen** [comment]
Fixed.

Note 32bit support is completely untested (and it has some special code in the driver). Let me know if it works.
