### ISSUE TITLE
libipt.so.1  and libipt.so.0 : library mismatch

### ISSUE THREAD

**Issue by sid7954** [andikleen/simple-pt#10]
On running a sample trace, sudo ./sptcmd -c ls ls, the trace is getting captured succesfully. However on decoding the trace using 

sudo ./sptdecode --sideband ptout.sideband --pt ptout.0 | less

an error is displayed regarding libipt:

./sptdecode: error while loading shared libraries: libipt.so.1: cannot open shared object file: No such file or directory

On checking for if libipt is correctly installed, using sudo ldconfig -p | grep libipt, 

libiptc.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libiptc.so.0

I guess this is some mismatch due to libipt.so.0 and libipt.so.1. How should I resolve this?

**Comment by andikleen** [comment]
On Wed, May 10, 2017 at 07:18:01AM -0700, sid7954 wrote:
> On running a sample trace, sudo ./sptcmd -c ls ls, the trace is getting
> captured succesfully. However on decoding the trace using
> 
> sudo ./sptdecode --sideband ptout.sideband --pt ptout.0 | less
> 
> an error is displayed regarding libipt:
> 
> ./sptdecode: error while loading shared libraries: libipt.so.1: cannot open
> shared object file: No such file or directory
> 
> On checking for if libipt is correctly installed, using sudo ldconfig -p | grep
> libipt,
> 
> libiptc.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libiptc.so.0
> 
> I guess this is some mismatch due to libipt.so.0 and libipt.so.1. How should I
> resolve this?

I only have libipt.so.1 and not libiptc.so.0. 

Maybe it's another recent bug in processor
trace. Can you go back further in the commits (maybe ~1-2 months) and see
if that fixes it?

-Andi

**Comment by sid7954** [comment]
What commit are you using?

I am currently using  b08d7bf362eb07

**Comment by sid7954** [comment]
We have currently installed the latest version of simple-pt (6f2c9a366baeeebbe66e33948b671d721bf5efda) and am using this [commit](https://github.com/01org/processor-trace/commit/b08d7bf362eb0705cac5fd064af48e4c4bb48955) of libipt as you had suggested. The earlier error of mismatching libipt libraries are now resolved. However on running the tester,  the decoding is failing without any verbose error. We are guessing it has something to do with the error (msr: msr=123 -> deadbeef failed ). Also there are some warnings thrown on the system calls used in loop.c (see error log below).

We also came across an earlier blog post on simple-pt (https://tthtlc.wordpress.com/2016/01/26/intel-processor-trace-how-to-use-it/) and tried to go back to the version in Jan,2016 to replicate the output in the stest.out file as shown there. However due to a mismatching version of the processor-trace branch, we were not able to make simple-pt user tools (undefined reference to `pt_insn_get_cr3') . 

Any hint on how to solve this will be greatly appreciated. We are happy to provide you with more information or/and take this discussion offline.

Thanks for your support.

-------------

```
+ trap failed ERR 0
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:.
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:.
+ ./TEST-FTRACE
     TEST-FTRACE-21821 [000] .... 93363.753721: msr: msr=123 -> deadbeef failed
     TEST-FTRACE-21821 [000] .... 93363.753722: process_cr3: pid=123 cr3=12345678, comm=foo
     TEST-FTRACE-21821 [000] .... 93363.753722: exec_cr3: cr3=deadbeef, pid=0, fn=bar
           <...>-21826 [002] .... 93363.753882: exec_cr3: cr3=43a502000, pid=0, fn=/bin/cat
     TEST-FTRACE-21821 [000] .... 93363.753723: mmap_cr3: cr3=deadbeef, pgoff=1, addr=2, len=1000, pid=789 fn=bar
           <...>-21826 [002] d... 93363.753863: mmap_cr3: cr3=43a502000, pgoff=0, addr=400000, len=c000, pid=21826 fn=/bin/cat
           <...>-21826 [002] d... 93363.753868: mmap_cr3: cr3=43a502000, pgoff=0, addr=7ffb40004000, len=228000, pid=21826 fn=/lib/x86_64-linux-gnu/ld-2.23.so
           <...>-21826 [002] d... 93363.753911: mmap_cr3: cr3=43a502000, pgoff=0, addr=7ffb3fc3b000, len=3c9000, pid=21826 fn=/lib/x86_64-linux-gnu/libc-2.23.so
SUCCEEDED
+ PREFIX=stest
+ EXTRA='-t   '
+ STDCMD=loop
+ CMD=loop
+ gcc -o loop loop.c -g
loop.c: In function ‘main’:
loop.c:9:2: warning: implicit declaration of function ‘prctl’ [-Wimplicit-function-declaration]
  prctl(12341234); /* marker 1 */
  ^
loop.c:12:2: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
  write(1, "foo\n", 4);
  ^
loop.c:13:2: warning: implicit declaration of function ‘personality’ [-Wimplicit-function-declaration]
  personality(21212212); /* marker 2 */
  ^
+ run
+ sptcmd -t -o stest taskset -c 0 loop
Wrote initial process maps to stest.maps
foo
cpu   0 offset  27440,    26 KB, writing to stest.0
cpu   1 offset  39968,    39 KB, writing to stest.1
cpu   2 offset   9632,     9 KB, writing to stest.2
cpu   3 offset  34032,    33 KB, writing to stest.3
cpu   4 offset    448,     0 KB, writing to stest.4
cpu   5 offset   5248,     5 KB, writing to stest.5
cpu   6 offset    992,     0 KB, writing to stest.6
cpu   7 offset    512,     0 KB, writing to stest.7
Wrote sideband to stest.sideband
+ sptdecode --sideband stest.sideband --pt stest.0
+ grep -q '__libc_start_main.*main' stest.out
++ failed
++ echo FAILED
FAILED
++ exit 1
+ failed
+ echo FAILED
FAILED
+ exit 1
```

**Comment by andikleen** [comment]
The TEST-FTRACE test succeeded. You also collected PT data. Not sure why the last test failed, but I've seen it fail before too. 

Try running something longer like sptcmd sleep 1 and look at the output.
