### ISSUE TITLE
Trace Multi-Threaded Programs

### ISSUE THREAD

**Issue by albertschulz** [andikleen/simple-pt#12]
Does the current version support tracing of multi threaded programs?

**Comment by andikleen** [comment]
Yes it does.

However it only prints them at a process granularity.

**Comment by albertschulz** [comment]
Thanks for the quick answer.

How would you recognize thread switches in the trace data? Process switches are obvious, since the produce PIP packets, but thread switches won't since the CR3 Register value is not changed.
Wouldn't we also need a CALL/RET decoding stack per thread in order to do the decoding properly, since otherwise the compressed returns of one thread would lead to "jump" to the position of another thread?

**Comment by albertschulz** [comment]
I showed the issue in a small decoding example: [Thread Issue.pdf](https://github.com/andikleen/simple-pt/files/1025445/Thread.Issue.pdf)

**Comment by andikleen** [comment]
If you trace the kernel too you can see it's executing the context switch code.
If you filter out the kernel there is no way with simple-pt because it doesn't have a context switch hook (unlike perf pt)

In an upcoming version it will support printing disable/enable events, so it can be seen that the kernel was entered even in this case. It won't be able to distinguish context switches from other interrupts though,

**Comment by albertschulz** [comment]
Okay I get that, so this is like a higher level of decoding, where you get to known which code is actually executed in order to figure out the user threads.
Maybe this question goes a little bit to deep into actual packet decoding, 
But let me come back to the packet decoding part: the decoder which be able to determine the correct return addresses anyhow, even when the user threads switches. Do you think a single RET Buffer is sufficient when decoding? Do you know about the behavior of the Intel PT Processing engine? I could imagine that instead of sending those "short single bit" RETurns, where the decoder has to figure out the return adress by itself, the trace data could kind of flush its internal state and send the full return address after a thread switch

**Comment by andikleen** [comment]
Yes the return stack is automatically flushed in this case, without needing sideband information.
