### ISSUE TITLE
Missing branches in decoded trace

### ISSUE THREAD

**Issue by bastoica** [andikleen/simple-pt#13]
Hi Andi,

Consider this code snippet compiled with no optimizations (i.e., `gcc -g snippet.c`). You can ignore the code inside the `if then` and `if else` basic blocks as it is not important. The main point is that the loop checks the branch condition at each iteration and then either:
1.  falls through the `then` basic block on even iterations (`if` branch taken), or
2. jumps to the `else` basic block on odd iterations (`if` branch not taken)

does that for 500,000,000 times and ends with a jump to the `return 0;` (i.e., loop branch becomes "not taken").

```
int main() {
	volatile int i=0, a=1, b=2, n=500000000;
	for (i=0; i<n; ++i) { // loop branch: taken (present in decoded trace)
		a++;
		a--;
		if (b<a) {    // if branch: taken (present in decoded trace)
			b=a*a-2*b;
			a=b*b*b-a*a-3;
		}
		else {        // if branch: not taken (not present in decoded trace)
			a=b*b-2*a;
			b=a*a*a - b*b -3;
		}	
	}
	return 0;
}
```

Given this intended execution pattern, when tracing and decoding we would expect to see an output like this (simplified for clarity, the RIPs of the dynamic/executed basic blocks are actually printed):
```
loop branch: taken
if branch:   taken
loop branch: taken
if branch:   not taken
loop branch: taken
if branch:   taken
loop branch: taken
if branch:   not taken
....
loop branch: not taken
```
Instead, we only see the taken loop branch and the taken if branch in an arbitrary order:
```
loop branch: taken
loop branch: taken
loop branch: taken
loop branch: taken
if branch:   taken
loop branch: taken
if branch:   taken
loop branch: taken
loop branch: taken
loop branch: taken
...
```
Moreover, there are far less than `2 * 500,000,000 + 1` entries in the output file, the trace doesn't end with the `loop branch: not taken` and successive runs yield different decoded outputs.... Intel PT's documentation mentions something about not capturing the prefix of the trace, but says nothing about the suffix, or about sampling branches or any kind of randomness in the tracing process (or it's possible that we misunderstood the documentation : -) ). 

And that's not all. When we change to code to get rid of the `a++` and `a--` lines inside the loop (i.e., first 2 lines after the `for` instruction), we start to see the "not taken" branch of the `if` statement from time to time, but still everything is printed in an arbitrary order: 
```
loop branch: taken
if branch:   not taken
loop branch: taken
loop branch: taken
loop branch: taken
if branch:   taken
loop branch: taken
if branch:   taken
loop branch: taken
loop branch: taken
if branch:   not taken
loop branch: taken
...
```

This is a bit confusing and maybe we're not using correct tracing / decoding arguments. As far as our understanding goes, both conditional jumps (loop and `if` statement) should be captured by Intel PT along with their direction  (i.e., taken / not taken) **at each iteration**. Then, the decoder should be able to tell **which basic blocks execute at each iteration based on the direction of the two branches** and print out the starting RIP of each such block. 

What are we missing?
Thanks.

P.S. We are currently running https://github.com/andikleen/simple-pt/commit/7e478000810d8eafba8518d1213d121c3d058458

**Comment by bastoica** [comment]
We checked the encoded output of Intel PT and we can clearly distinguish recurring patterns of 80 bytes which is roughly the same size of the disassembled fraction of the loop executing at each iteration (95 bytes) so the hardware appears to trace correctly.

**Comment by andikleen** [comment]
By default sptdecode just prints function calls, or interruptions There aren't any calls in your loop, so you only see the interrupts. If you want to see every instruction use -i
