### ISSUE TITLE
No trace captured when tracing a single function: onoff.c

### ISSUE THREAD

**Issue by sid7954** [andikleen/simple-pt#14]
The code provided in onoff.c does not capturing the trace and write to the ptout.(CPU NUMBER) files. I also tried writing into the /sys/module/simple_pt/parameters/log_dump file in order to dump the captured trace. However neither of the following seem to capture the trace and write to the ptout files. 
```
//Remaining Functions same as in onoff.c
void dump(int flag)
{
    sptcmd(flag,"/sys/module/simple_pt/parameters/log_dump");
}

int main(){
onoff(1);
// Disable clear on start
disable_clear();
start(1);
f1();
write(1, "foo\n", 4);
onoff(0);
dump(1);
}
```

```
//Remaining Functions same as in onoff.c
void dump(int flag)
{
    sptcmd(flag,"/sys/module/simple_pt/parameters/log_dump");
}

int main(){
onoff(1);
// Disable clear on start
disable_clear();
start(1);
f1();
write(1, "foo\n", 4);
dump(1);
onoff(0);
}
```

**Comment by andikleen** [comment]
Use sptcmd to capture the trace files.

Otherwise you would need to reimplement parts of sptcmd in C
