### ISSUE TITLE
insmod simple_pt.ko failed.

### ISSUE THREAD

**Issue by Alex287** [andikleen/simple-pt#18]
I was follow the simple-pt install guidence, and everything went well until the last step.

When I executed "./ptfeature", it got an output of "No PT support", and I find the simple_pt.ko is not in the kernel module. 

So I run "insmod simple_pt.ko", the output is as follows:
"insmod:ERROR: could not insert module :Input/output error"

And then I run dmesg to see the kernel log, the output is as follows:
![qq 20180409165454](https://user-images.githubusercontent.com/26807502/38488812-27fa2288-3c17-11e8-90f9-9751c99e971b.png)

By the way, I was install simple-pt in a kvm-qemu virtual machine.

**Comment by andikleen** [comment]
KVM doesn't support PT currently. Run it on a native system
