### ISSUE TITLE
timestamp issue

### ISSUE THREAD

**Issue by heartever** [andikleen/simple-pt#19]
While I am running the test (using the default parameters in simple-pt.c)
```
sudo ./sptcmd -c ls ls
sudo ./sptdecode --sideband ptout.sideband --pt ptout.0 | less
```
There are no (or only very few) timestamps shown in the output. Could you shed some light on the possible causes? Does simple-pt support using CYC/MTC packets?

Thanks

**Comment by andikleen** [comment]
Yes it does. See the manpage.

**Comment by heartever** [comment]
I ran a trace with
```
sudo ./sptcmd -c ls taskset -c 1 ls
```
Then using 
```
sudo ./fastdecode ptout.1
```
I can see many (several hundreds) tsc packets. However using 
```
sudo ./sptdecode --sideband ptout.sideband --pt ptout.1
```
only very few (< 10) lines have timestamp.

Could you provide a sample use case of showing timestamp when using ``sptdecode``?
