### ISSUE TITLE
undefined reference to `pt_insn_get_cr3'

### ISSUE THREAD

**Issue by tosanjay** [andikleen/simple-pt#2]
Hi,
While compiling simple_pt, at the stage "make user UDIS86=1", I got the following error:
simple-pt/sptdecode.c:437: undefined reference to `pt_insn_get_cr3'
collect2: error: ld returned 1 exit status
make: **\* [sptdecode] Error 1

I have followed steps described in the README. Help is required.
thanks

**Comment by andikleen** [comment]
You built against the wrong version of libipt (processor-trace)
Only my branch has pt_insn_get_cr3 currently

You may need to check out the right branch and rebuilt processor-trace

**Comment by tosanjay** [comment]
ok. thanks.

**Comment by xdje42** [comment]
Still an issue, and I can't find a libipt branch with pt_insn_get_cr3.
Where would I find it?

**Comment by andikleen** [comment]
On Sat, Dec 17, 2016 at 01:58:54PM -0800, xdje42 wrote:
> Still an issue, and I can't find a libipt branch with pt_insn_get_cr3.
> Where would I find it?

Follow the first paragraph in "Installation"

**Comment by andresjpico-zz** [comment]
Hello,

I followed the instructions but when running "sudo ./tester" I get the error below, do you know what may be wrong with my setup?:

Wrote sideband to stest.sideband
+ sptdecode --sideband stest.sideband --pt stest.0
sptdecode: symbol lookup error: sptdecode: undefined symbol: pt_insn_get_cr3
+ failed
+ echo FAILED
FAILED
+ exit 1

**Comment by andikleen** [comment]
On Fri, Jan 20, 2017 at 01:09:41PM -0800, apicochavez wrote:
> Hello,
> 
> I followed the instructions but when running "sudo ./tester" I get the error
> below, do you know what may be wrong with my setup?:
> 
> Wrote sideband to stest.sideband
> 
>   • sptdecode --sideband stest.sideband --pt stest.0
>     sptdecode: symbol lookup error: sptdecode: undefined symbol:
>     pt_insn_get_cr3
>   • failed
>   • echo FAILED
>     FAILED
>   • exit 1

You built libipt from the wrong branch. Please follow the instructions
completely.

-Andi
