### ISSUE TITLE
build issue: cannot find dwarf headers

### ISSUE THREAD

**Issue by albertschulz** [andikleen/simple-pt#7]
I can't build the user tools using 'make user'
I get the following errors:
dwarf.c:32:31: fatal error: libdwarf/libdwarf.h: Datei oder Verzeichnis nicht gefunden
dwarf.c:33:28: fatal error: libdwarf/dwarf.h: Datei oder Verzeichnis nicht gefunden

This means it can not find the header files. Changing the includes to libdwarf.h instead of libdwarf/libdwarf.h solves this issue.
Why is that?

**Comment by andikleen** [comment]
Obviously because on my system and every one else who built simple-pt before it's in libdwarf/libdwarf.h

What distribution / libdwarf version is that?

I suppose could add a -I /usr/include/libdwarf -I /usr/local/include/libdwarf.h to the Makefile, then the directory could be removed.
